---
name: push workflow

on: [push]

env:
  node: 16
jobs:
  build_and_push_editor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
      - name: npm ci
        run: npm ci --prefer-offline --no-audit
      - name: build editor
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build editor